// <auto-generated />
using System;
using DiplomaProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiplomaProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260521185013_RecreateDeletedTable")]
    partial class RecreateDeletedTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DiplomaProject.Models.Entities.TabItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("InstanceId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tabs");
                });

            modelBuilder.Entity("DiplomaProject.Models.Entities.TestStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PdfPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RawResponse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TabItemId")
                        .HasColumnType("int");

                    b.Property<string>("TestsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TabItemId")
                        .IsUnique();

                    b.ToTable("TestStates");
                });

            modelBuilder.Entity("TestAnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttemptId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("QuestionIndex")
                        .HasColumnType("int");

                    b.Property<int>("SelectedAnswerIndex")
                        .HasColumnType("int");

                    b.Property<int?>("TestAttemptEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestAttemptEntityId");

                    b.ToTable("TestAnswerEntity");
                });

            modelBuilder.Entity("TestAttemptEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("TestStateEntityId")
                        .HasColumnType("int");

                    b.Property<int>("TestStateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestStateEntityId");

                    b.ToTable("TestAttemptEntity");
                });

            modelBuilder.Entity("DiplomaProject.Models.Entities.TestStateEntity", b =>
                {
                    b.HasOne("DiplomaProject.Models.Entities.TabItemEntity", "TabItem")
                        .WithOne("TestState")
                        .HasForeignKey("DiplomaProject.Models.Entities.TestStateEntity", "TabItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TabItem");
                });

            modelBuilder.Entity("TestAnswerEntity", b =>
                {
                    b.HasOne("TestAttemptEntity", null)
                        .WithMany("Answers")
                        .HasForeignKey("TestAttemptEntityId");
                });

            modelBuilder.Entity("TestAttemptEntity", b =>
                {
                    b.HasOne("DiplomaProject.Models.Entities.TestStateEntity", null)
                        .WithMany("Attempts")
                        .HasForeignKey("TestStateEntityId");
                });

            modelBuilder.Entity("DiplomaProject.Models.Entities.TabItemEntity", b =>
                {
                    b.Navigation("TestState")
                        .IsRequired();
                });

            modelBuilder.Entity("DiplomaProject.Models.Entities.TestStateEntity", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("TestAttemptEntity", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
